name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - numpy ==1.21.4
  - matplotlib
  - pandas
  - ipycanvas
  - scikit-learn ==1.1.1
