name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - numpy >=1.17.3,<1.25.0
  - matplotlib
  - pandas
  - ipycanvas
  - scikit-learn >=1.3.0
